name: Paperv1_21_11Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v6

      - name: Javaをセットアップ
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: GitのコミットIDを取得
        id: git
        run: echo "GIT_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: ビルド
        run: ./gradlew :paper:v1_21_11:build -PgitCommit=${GIT_COMMIT}

      - name: 配置
        uses: actions/upload-artifact@v6
        with:
          name: RandomTP-Paper1.21.11
          path: paper/v1_21_11/build/libs/*.jar